version: '3.6'

services:

  chatgpt:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    platform: linux/amd64
    ports:
      - 10000:3000
    environment:
      - 'OPENAI_API_KEY=000000000000000'
      - 'OPENAI_API_HOST=http://api:8000'

  api:
    build: .
    volumes:
      - '/media/NAS/Docker/Docker compose/gpt4all/models:/models'
    ports:
      - 8009:8000
    environment:
      - MODEL="/media/NAS/Docker/Docker compose/gpt4all/models/wizardlm-13b-v1.1-superhot-8k.ggmlv3.q4_0.bin"
